language: android
jdk:
    - oraclejdk8
android:
    components:
        - platform-tools
        - tools
        - build-tools-27.0.2
        - android-27
        - extra-google-google_play_services
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-android-support
        - addon-google_apis-google-27
script:
    ./gradlew build assembleAndroidTest --stacktrace
